# Estar en el repositorio qu tienes el archivo --> cd activities 
# docker build .

FROM ubuntu:18.04 

RUN apt-get update
#RUN echo "hello1"
RUN apt-get install -y nginx
# run echo "hello2"
EXPOSE 80
ENTRYPOINT /usr/sbin/nginx -g "daemon off;" 

# docker images

#ponerle nombre a la imagen
#docker build -t myimage .