# Estar en el repositorio qu tienes el archivo --> cd activities 
# docker build .

FROM ubuntu:18.04 

RUN apt-get update
#RUN echo "hello1"
RUN apt-get install -y nginx


# tiempo de ejecucion 
# run echo "hello2"
EXPOSE 80
ENTRYPOINT /usr/sbin/nginx -g "daemon off;" 



# docker images
#ponerle nombre a la imagen
#docker build -t myimage .
# cambiar la version  docker tag e62851ae9148 myimage:latest 

#EJECUTAR
#docker run -d myimage
#docker ps
#PARAR
#docker stop myimage  