#
FROM ubuntu:20.04 
RUN apt-get update
RUN apt-get install -y git

# Define el comando a ejecutar cuando el contenedor se inicia

CMD git --version

# ejeuctar 
#docker build -it gitfile
#entrar dentro
#docker run -it gitfile bash