
FROM python

COPY script.py / 

ENTRYPOINT python script.py

#EJERCICIO FINAL
# 1. Cogemos una imagen con python
# 2. Hacemos un entregable con python
# 3. sHacer ENTRYPOINT


# docker build -it imagenpython
# docker run imagenpython 1 2

#Construir un script en python que acepte dos números como parámetros e imprima el resultado de la suma
##normal

#Construir una imagen docker que contenga dicho python script
##Coger una imagen que ya tenga python
## Añadir el script dentro de la imagen
## crear imegen

#Cuando se ejecute el contendor docker, este debe invocar al script pasando como parámetro ambos números.
## aejecutar el contendor y que ejecure el script